# Generated by Django 5.1 on 2024-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.BinaryField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
